version: '3.8'

services:
  librarydb:
    image: postgres:16.3
    container_name: librarydb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - librarydb-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - librarydb
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  librarydb-data:
  pgadmin-data: